name: generate snake
on:
  schedule:
    - cron: "0 */24 * * *"  
  workflow_dispatch:      
  push:
    branches:
      - main
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate snake svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#1A6FB5&color_dots=#ebedf0,#b8e6e5,#5fcfcd,#0ABFBC,#089a98
            dist/github-snake-dark.svg?color_snake=#1A6FB5&color_dots=#161b22,#0a4f4e,#0a9290,#0ABFBC,#3dd6d4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
